# Generated by Django 6.0.3 on 2026-04-14 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synchronous_sessions_attended', models.PositiveIntegerField(default=0)),
                ('synchronous_sessions_total', models.PositiveIntegerField(default=3)),
                ('asynchronous_activities_completed', models.PositiveIntegerField(default=0)),
                ('asynchronous_activities_total', models.PositiveIntegerField(default=4)),
                ('final_exam_score', models.FloatField(default=0)),
                ('minimum_attendance_percentage', models.PositiveIntegerField(default=70)),
                ('minimum_exam_score', models.PositiveIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__username'],
            },
        ),
    ]
