# Generated by Django 6.0.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pregunta_seguridad',
            field=models.CharField(choices=[('mascota', 'Como se llama tu primera mascota?'), ('madre', 'Cual es el segundo nombre de tu madre?'), ('ciudad', 'En que ciudad naciste?')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('admin_academico', 'Administrador academico')], default='estudiante', max_length=20),
        ),
    ]
