# Generated by Django 6.0.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duracion en minutos'),
        ),
    ]
