# Generated by Django 6.0.3 on 2026-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_academic", "0003_test_created_by_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("short_text", "Respuesta corta"),
                    ("long_text", "Respuesta larga"),
                    ("multiple_choice", "Seleccion multiple"),
                    ("checkboxes", "Casillas de verificacion"),
                    ("dropdown", "Lista desplegable"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="selected_answer_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="text_response",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to="tests_academic.answer",
            ),
        ),
    ]
