# Generated by Django 5.2.10 on 2026-04-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_academic', '0004_question_question_type_question_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'order', 'id']},
        ),
    ]
