# Generated by Django 5.2.10 on 2026-04-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseactivity'),
        ('tests_academic', '0005_alter_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course'),
        ),
        migrations.AddField(
            model_name='test',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('conocimientos', 'Conocimientos'), ('vocacional', 'Vocacional')], default='conocimientos', max_length=50),
        ),
    ]
