# Generated by Django 5.2.10 on 2026-04-24 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.TextField(default='Bienvenido a este curso.', help_text='Mensaje inicial que veran los usuarios asignados.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'estudiante'}, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'profesor'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['name'],
            },
        ),
    ]
