# Generated by Django 5.2.10 on 2026-04-28 00:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='course_submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip', 'rar', 'txt', 'jpg', 'png'])])),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.courseactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de actividad',
                'verbose_name_plural': 'Entregas de actividades',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_submission_per_student')],
            },
        ),
    ]
