# Generated by Django 5.2.10 on 2026-04-28 02:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseactivitysubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivitysubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='courseactivitysubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseactivitysubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_activity_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseactivitysubmission',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
    ]
