# Generated by Django 5.2.10 on 2026-04-28 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseactivitysubmission_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('class_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='courses.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'tipo_usuario': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase programada',
                'verbose_name_plural': 'Clases programadas',
                'ordering': ['class_date', 'session_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_course_class_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_class_attendances', to=settings.AUTH_USER_MODEL)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.courseclasssession')),
            ],
            options={
                'verbose_name': 'Asistencia de clase',
                'verbose_name_plural': 'Asistencias de clases',
                'ordering': ['student__last_name', 'student__first_name', 'student__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='courseclasssession',
            constraint=models.UniqueConstraint(fields=('course', 'class_date'), name='unique_class_date_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseclasssession',
            constraint=models.UniqueConstraint(fields=('course', 'session_number'), name='unique_session_number_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseclassattendance',
            constraint=models.UniqueConstraint(fields=('class_session', 'student'), name='unique_attendance_per_student_and_class'),
        ),
    ]
