# Generated by Django 5.2.13 on 2026-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseclasssession_courseclassattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_training',
            field=models.BooleanField(default=False, help_text='Marca este curso para mostrarlo en el apartado de capacitacion.', verbose_name='Es capacitacion'),
        ),
    ]
