# Generated by Django 5.2.13 on 2026-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_seed_default_leveling_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_training',
            field=models.BooleanField(default=False, help_text='Marca este curso para mostrarlo en el apartado de induccion.', verbose_name='Es induccion'),
        ),
    ]
