# Generated by Django 5.2.13 on 2026-05-07 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_is_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Curso de induccion',
                'verbose_name_plural': 'Cursos de induccion',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Aula')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'estudiante'}, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes reprobados')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'profesor'}, related_name='classrooms_taught', to=settings.AUTH_USER_MODEL, verbose_name='Profesores asignados')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.classroom', verbose_name='Aula de nivelacion'),
        ),
    ]
