# Generated by Django 6.0.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='source_phase',
            field=models.CharField(blank=True, choices=[('induction', 'Induccion'), ('leveling', 'Nivelacion')], max_length=50),
        ),
    ]
