# Generated by Django 6.0.3 on 2026-03-30 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('test', 'Test'), ('induction', 'Inducción'), ('leveling', 'Nivelación')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'phase'],
                'constraints': [models.UniqueConstraint(fields=('student', 'phase'), name='unique_progress_per_phase')],
            },
        ),
    ]
