# Generated by Django 6.0.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='phase',
            field=models.CharField(choices=[('test', 'Test'), ('induction', 'Induccion'), ('leveling', 'Nivelacion')], max_length=50),
        ),
    ]
