# Generated by Django 5.2.13 on 2026-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_induction_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='phase',
            field=models.CharField(choices=[('test', 'Test'), ('induction', 'Induccion'), ('leveling', 'Nivelacion')], max_length=50),
        ),
    ]
